### ISSUE TITLE
New RNAseq library_preparation_kits

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#12]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq

### Describe the change request (use a numbered list if many).

Add 

- Chromium Next GEM Single Cell 3’ GEM, Library & Gel Bead Kit v3.1, 16 rxns PN-1000121
- Chromium Next GEM Single Cell 3' HT Kit v3.1, 48 rxns PN-1000348 | 8 rxns PN-1000370

**Comment by johardi** [comment]
We have a standard string pattern to label library kits: `manufacturer; model/name; product code`.

Below are the new kit labels following the pattern:
* 10X Genomics; Chromium Next GEM Single Cell 3’ GEM, Library & Gel Bead Kit v3.1, 16 rxns; PN 1000121
* 10X Genomics; Chromium Next GEM Single Cell 3' HT Kit v3.1, 48 rxns; PN 1000348
* 10X Genomics; Chromium Next GEM Single Cell 3' HT Kit v3.1, 8 rxns; PN 1000370

@HerrLufty Could you please confirm these to the requester? 

PS. I need to break down the last library kit item because it contains two product numbers (PN).

**Comment by HerrLufty** [comment]
Confirmed...go ahead with the add
